## --------------------以下为个人配置-------------------- ##

# 锚点，用于简化配置
# for proxy-providers
pp: &pp {type: http, interval: 86400, proxy: DIRECT, "health-check": {enable: true, url: http://www.gstatic.com/generate_204, interval: 300}}
# for proxy-groups 
pg_fb: &pg_fb {type: fallback, url: http://www.gstatic.com/generate_204, tolerance: 20, interval: 300}
pg_ut: &pg_ut {type: url-test, url: http://www.gstatic.com/generate_204, tolerance: 20, interval: 300}
# for rule-providers
ip_mrs: &ip_mrs {type: http, interval: 86400, behavior: ipcidr, format: mrs}
domain_mrs: &domain_mrs {type: http, interval: 86400, behavior: domain, format: mrs}
domain_yaml: &domain_yaml {type: http, interval: 86400, behavior: domain, format: yaml}
class_yaml: &class_yaml {type: http, interval: 86400, behavior: classical, format: yaml}
# 机场代理地址
proxy-providers:  
  Proxies: {<<: *pp, url: ""}
  SS+TLS: {<<: *pp, url: ""}
# 机场代理策略组分组
proxy-groups:
  - {name: Global, type: select, proxies: [HK, JP, US, SG, TW, UN, DIRECT, Proxies], use: [SS+TLS]}
  - {name: Telegram, type: select, proxies: [SG, Global, HK, JP, US, TW]}
  - {name: AI, type: select, proxies: [US, Global, HK, JP, SG, TW]}
  - {name: VPS, type: select, proxies: [DIRECT, Global, HK, JP, US, SG, TW, UN]}
  - {name: Emby, type: select, proxies: [DIRECT, 实验线路0.2X, Global], use: [SS+TLS]}
  - {name: Apple, type: select, proxies: [DIRECT, Global, HK, JP, US, SG, TW]}
  - {name: OneDrive, type: select, proxies: [DIRECT, Global]}
  - {name: Speedtest, type: select, proxies: [DIRECT, HK, JP, US, SG, TW, UN, 高级线路, 标准线路, 实验线路0.2X, Proxies], use: [SS+TLS]}
  - {name: Final, type: select, proxies: [DIRECT, Global, REJECT]}
  - {name: UN, type: select, filter: "^(?!.*?(香港|日本|新加坡|美国|台湾|实验)).*(标准)", use: [Proxies]}
  - {name: HK, <<: *pg_ut, filter: "(香港).*(高级)", use: [Proxies]}
  - {name: JP, <<: *pg_ut, filter: "(日本).*(高级)", use: [Proxies]}
  - {name: US, <<: *pg_ut, filter: "(美国).*(高级)", use: [Proxies]}
  - {name: SG, <<: *pg_ut, filter: "(新加坡).*(高级)", use: [Proxies]}
  - {name: TW, <<: *pg_ut, filter: "(台湾).*(高级)", use: [Proxies]}
  - {name: 高级线路, filter: "高级", type: select, use: [Proxies]} 
  - {name: 标准线路, filter: "标准", type: select, use: [Proxies]} 
  - {name: 实验线路0.2X, filter: "实验", type: select, use: [Proxies]} 
  - {name: Proxies, type: select, use: [Proxies]} 
# 规则订阅
rule-providers:
  OpenAI: {<<: *class_yaml, url: "https://rule.kelee.one/Clash/OpenAI.yaml"} 
  Copilot: {<<: *class_yaml, url: "https://rule.kelee.one/Clash/Copilot.yaml"}
  Gemini: {<<: *class_yaml, url: "https://rule.kelee.one/Clash/Gemini.yaml"}
  Claude: {<<: *class_yaml, url: "https://rule.kelee.one/Clash/Claude.yaml"}
  Lan: {<<: *class_yaml, url: "https://rule.kelee.one/Clash/Lan.yaml"}
  Fix: {<<: *class_yaml, url: "https://rule.kelee.one/Clash/Direct.yaml"}
  Bing: {<<: *class_yaml, url: "https://rule.kelee.one/Clash/Bing.yaml"}
  Apple: {<<: *class_yaml, url: "https://rule.kelee.one/Clash/Apple.yaml"}
  OneDrive: {<<: *class_yaml, url: "https://rule.kelee.one/Clash/OneDrive.yaml"}
  GoogleVoice: {<<: *class_yaml, url: "https://rule.kelee.one/Clash/GoogleVoice.yaml"}
  Telegram: {<<: *class_yaml, url: "https://rule.kelee.one/Clash/Telegram.yaml"}
  Speedtest: {<<: *class_yaml, url: "https://rule.kelee.one/Clash/Speedtest.yaml"}
  WeChat: {<<: *class_yaml, url: "https://rule.kelee.one/Clash/WeChat.yaml"}
  IPTVMainland: {<<: *class_yaml, url: "https://rule.kelee.one/Clash/IPTVMainland.yaml"}
  ChinaMax: {<<: *class_yaml, url: "https://rule.kelee.one/Clash/ChinaMax.yaml"}
  IPTVOther: {<<: *class_yaml, url: "https://rule.kelee.one/Clash/IPTVOther.yaml"}
  Global: {<<: *class_yaml, url: "https://rule.kelee.one/Clash/Global.yaml"}
# 规则
rules:
  # 白名单
  - DOMAIN, feiyang.allinhub.dpdns.org, DIRECT
  - DOMAIN, update.code.visualstudio.com, DIRECT
  - DOMAIN-SUFFIX, msecnd.net, DIRECT
  - DOMAIN-SUFFIX, rztcd.com, DIRECT
  - DOMAIN-SUFFIX, cddyjy.com, DIRECT
  - DOMAIN-SUFFIX, bendibao.com, DIRECT
  - DOMAIN-SUFFIX, cdrcbank.com, DIRECT
  - DOMAIN-SUFFIX, splashtop.com, DIRECT
  # 黑名单
  - DOMAIN, img.noobzone.ru, GLOBAL
  - DOMAIN, connect.garmin.com, Global
  - DOMAIN, sso.garmin.com, Global
  - DOMAIN-SUFFIX, mailjet.com, Global
  - DOMAIN-SUFFIX, proton.me, Global
  - DOMAIN-SUFFIX, oplist.org, Global
  - DOMAIN-SUFFIX, openlist.team, Global
  - DOMAIN-SUFFIX, readest.com, Global
  - DOMAIN-SUFFIX, mcp.so, Global
  - DOMAIN-SUFFIX, nsloon.app, Global
  - DOMAIN-SUFFIX, kelee.one, Global
  - DOMAIN-SUFFIX, annas-archive.org, Global
  - DOMAIN-SUFFIX, firefly-iii.org, Global
  - DOMAIN-SUFFIX, allinhub.dpdns.org, Global
  - DOMAIN-SUFFIX, amysecure.com, Global
  - DOMAIN-SUFFIX, paopao.dog, Global
  - DOMAIN-SUFFIX, api-flowercloud.com, Global
  - DOMAIN-SUFFIX, rutracker.org, Global
  - DOMAIN-SUFFIX, linux.do, Global
  - DOMAIN-SUFFIX, imazing.com, GLOBAL
  # Emby
  - DOMAIN-SUFFIX, uhdnow.com, Emby
  # JavBus
  - DOMAIN-SUFFIX, dmm.co.jp, JP
  - DOMAIN-SUFFIX, mgstage.com, JP
  - DOMAIN-SUFFIX, javbus.com, Global
  - DOMAIN-SUFFIX, javbus22.com, Global
  - DOMAIN-SUFFIX, missav.com, Global
  - DOMAIN-SUFFIX, eightcha.com, Global
  - DOMAIN-SUFFIX, javdb.com, Global
  - DOMAIN-SUFFIX, jable.tv, Global
  - DOMAIN-SUFFIX, avgle.com, Global
  - DOMAIN-SUFFIX, javlibrary.com, Global
  - DOMAIN-SUFFIX, jav.guru, Global
  - DOMAIN-SUFFIX, netflav.com, Global
  - DOMAIN-SUFFIX, javday.tv, Global
  # > VPS
  - IP-CIDR, 152.70.91.193/32, VPS, no-resolve
  # > AI
  - RULE-SET, OpenAI, AI
  - RULE-SET, Copilot, AI
  - RULE-SET, Gemini, AI
  - RULE-SET, Claude, AI
  # 局域网
  - RULE-SET, Lan, DIRECT
  # 后续规则修正
  - RULE-SET, Fix, DIRECT
  # Bing
  - RULE-SET, Bing, DIRECT
  # Apple
  - RULE-SET, Apple, Apple
  # Onedrive
  - RULE-SET, OneDrive, OneDrive
  # GoogleVoice
  - RULE-SET, GoogleVoice, US
  # Telegram
  - RULE-SET, Telegram, Telegram
  # Speedtest
  - RULE-SET, Speedtest, Speedtest
  # 微信
  - RULE-SET, WeChat, DIRECT
  # China
  - RULE-SET, IPTVMainland, DIRECT
  - RULE-SET, ChinaMax, DIRECT
  # Global
  - RULE-SET, IPTVOther, Global
  - RULE-SET, Global, Global
  - MATCH, Final
